# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json ./
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Ensure the entrypoint is executable
RUN chmod +x index.js

# Run the MCP server
CMD ["node", "index.js", "run"]
